version: '3'

services: 
  db: 
    image: "postgres"
    networks:
      - db_nw
    environment: 
      - POSTGRES_USER=jeeves
      - POSTGRES_PASSWORD=jeeves
  web: 
    build:
        context: ./server
    volumes:
      - ./server/:/server
      - node_modules:/server/node_modules
    networks:
      - db_nw
      - web_nw
    depends_on: 
      - db 
    environment: 
      - DB_HOST=db
      - DB_USERNAME=jeeves
      - DB_PASSWORD=jeeves
  nginx:
    image: "nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./.docker/conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - web
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  node_modules:
